
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/workspace/liuye/CPP_Project/cmakeinstall/cmake-3.29.2/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-28-generic - x86_64
...
